In [1]:
import numpy as np

In [4]:
arr = np.random.rand(5,4)

In [5]:
arr

array([[0.7962948 , 0.09539582, 0.20142034, 0.68692817],
       [0.44688555, 0.86444237, 0.96166913, 0.42376296],
       [0.86132484, 0.25725856, 0.16438187, 0.6476855 ],
       [0.25580843, 0.34157325, 0.2659809 , 0.02542912],
       [0.94896241, 0.35549531, 0.86511988, 0.95374304]])

In [6]:
arr[2,]

array([0.86132484, 0.25725856, 0.16438187, 0.6476855 ])

In [8]:
arr[:,1]

array([0.09539582, 0.86444237, 0.25725856, 0.34157325, 0.35549531])

In [11]:
arr[2:,1:3]

array([[0.25725856, 0.16438187],
       [0.34157325, 0.2659809 ],
       [0.35549531, 0.86511988]])

In [12]:
np.sum(arr) # functions

10.419562247710259

In [13]:
np.max(arr)

0.961669127642987

In [14]:
np.mean(arr)

0.520978112385513

In [17]:
arr2 = np.arange(5,20)

In [18]:
arr2


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
arr2 > 7

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [21]:
sum(arr2>7)

12

In [22]:
np.mean(arr2)

12.0

In [23]:
# more functions

In [24]:
arr1 =np.random.rand(3,4)

In [31]:
arr2 = np.random.rand(3,5)

In [32]:
arr1

array([[0.37123297, 0.81364031, 0.98513031, 0.97078397],
       [0.54452818, 0.04372243, 0.89341885, 0.70265875],
       [0.84601936, 0.63183938, 0.47717702, 0.32714669]])

In [33]:
arr2

array([[0.00977041, 0.9473577 , 0.43909877, 0.70183652, 0.87379936],
       [0.35543302, 0.1513968 , 0.24472262, 0.3369822 , 0.1397272 ],
       [0.99518316, 0.89194731, 0.81263196, 0.03304162, 0.0600091 ]])

In [34]:
# horizontal stacking
np.hstack((arr1,arr2))

array([[0.37123297, 0.81364031, 0.98513031, 0.97078397, 0.00977041,
        0.9473577 , 0.43909877, 0.70183652, 0.87379936],
       [0.54452818, 0.04372243, 0.89341885, 0.70265875, 0.35543302,
        0.1513968 , 0.24472262, 0.3369822 , 0.1397272 ],
       [0.84601936, 0.63183938, 0.47717702, 0.32714669, 0.99518316,
        0.89194731, 0.81263196, 0.03304162, 0.0600091 ]])

In [35]:
# vertical stacking

In [36]:
x = np.random.rand(3,4)

In [37]:
y = np.random.rand(4,4)

In [38]:
np.vstack((x,y))

array([[0.36103392, 0.91662947, 0.96715343, 0.00693546],
       [0.02508734, 0.25585111, 0.76189766, 0.22059162],
       [0.60831474, 0.87367326, 0.30752335, 0.09734185],
       [0.92633472, 0.36792595, 0.17202271, 0.96334607],
       [0.10961114, 0.33740664, 0.22739007, 0.63507961],
       [0.11495546, 0.19423771, 0.90335711, 0.47886563],
       [0.7809057 , 0.46977121, 0.18404311, 0.18688845]])

In [39]:
arr1 =np.random.rand(3,4)

In [40]:
a = 10* arr1

In [41]:
a

array([[8.7741443 , 0.21722616, 6.29699133, 5.50941474],
       [1.49572085, 5.72842635, 0.11659965, 8.51318641],
       [9.0035105 , 7.63818499, 6.01502348, 9.36474109]])

In [42]:
np.floor(a)

array([[8., 0., 6., 5.],
       [1., 5., 0., 8.],
       [9., 7., 6., 9.]])

In [43]:
np.ceil(a)

array([[ 9.,  1.,  7.,  6.],
       [ 2.,  6.,  1.,  9.],
       [10.,  8.,  7., 10.]])

# ROWWISE AND COLUMN WISE OPERATIONS


In [45]:
np.mean(a)

5.722764155260372

In [46]:
np.mean(a, axis =0) # 0 is for column

array([6.42445855, 4.52794583, 4.14287149, 7.79578075])

In [47]:
np.mean(a,axis =1) # 1 is for row

array([5.19944413, 3.96348332, 8.00536502])

In [48]:
np.cumsum(a)

array([ 8.7741443 ,  8.99137046, 15.28836179, 20.79777653, 22.29349738,
       28.02192374, 28.13852339, 36.6517098 , 45.6552203 , 53.29340529,
       59.30842877, 68.67316986])

In [49]:
np.cumsum(a,axis =0)

array([[ 8.7741443 ,  0.21722616,  6.29699133,  5.50941474],
       [10.26986516,  5.94565251,  6.41359098, 14.02260116],
       [19.27337566, 13.5838375 , 12.42861446, 23.38734225]])

In [50]:
a

array([[8.7741443 , 0.21722616, 6.29699133, 5.50941474],
       [1.49572085, 5.72842635, 0.11659965, 8.51318641],
       [9.0035105 , 7.63818499, 6.01502348, 9.36474109]])

In [51]:
for item in a:
    print(item)

[8.7741443  0.21722616 6.29699133 5.50941474]
[1.49572085 5.72842635 0.11659965 8.51318641]
[9.0035105  7.63818499 6.01502348 9.36474109]


In [52]:
for index, item in enumerate(a):
    print(index,item)

0 [8.7741443  0.21722616 6.29699133 5.50941474]
1 [1.49572085 5.72842635 0.11659965 8.51318641]
2 [9.0035105  7.63818499 6.01502348 9.36474109]


In [53]:
r = np.arange(4,16)

In [54]:
r

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
for index, item in enumerate(r):
    print(index,item)

0 4
1 5
2 6
3 7
4 8
5 9
6 10
7 11
8 12
9 13
10 14
11 15


In [56]:
r.shape

(12,)

In [57]:
r.size

12